### ISSUE TITLE
Gitlab group is not working

### ISSUE THREAD

**Issue by jwillmer** [mattermost/mattermost-plugin-gitlab#235]
If I add our group name into the group field we don't receive any notification. I tested it with upper and lowercase group name. Leaving the field blank allows us to receive notifications.

![image](https://user-images.githubusercontent.com/1503577/99959671-ba0c3b80-2d8b-11eb-9cd8-24e9cb059f37.png)

Our subscription looks like this: `/gitlab subscriptions add groupname`

**Comment by hanzei** [comment]
Are you using Version 1.3.0?

**Comment by hanzei** [comment]
Also: What GitLab version are you using?

**Comment by jwillmer** [comment]
I was on `GitLab (com.github.manland.mattermost-plugin-gitlab - 1.2.0)`. I update now and let you know if it works.

**Comment by DHaussermann** [comment]
Thanks @jwillmer for the report. It seems this issue also affects v1.3.0 I can also reproduce it with this version. I have created a jira issue here https://mattermost.atlassian.net/browse/MM-32680 to address this. 

cc @hanzei

**Comment by DHaussermann** [comment]
Hi @jwillmer,
It was brought to my attention this week that this issue was never closed. 

Please note that this issue was fixed in the `v1.4.0` release from October of 2021.  https://github.com/mattermost/mattermost-plugin-gitlab/releases/tag/v1.4.0

My apologies for not notifying you at the the time and closing the issue you reported.
