### ISSUE TITLE
Add html/markdown comment support

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-plugin-gitlab#423]
A customer has asked about the possibility to add support for markdown comments in gitlab issue posts inside of Mattermost as they use the comments to store meta info about their gitlab tickets. In gitlab (and github as well) these days the markdown comments will be correctly rendered, or not rendered to be more specific 😉 , so it woul follow suit with the correct rendering to also implement this in the plugin as well.

An example comment would simply look like this:

```
<!---
your comment goes here
and here
-->
```

Also inserting here to show github supporting this too:

**Comment by mickmister** [comment]
@svelle Thanks for reporting this. It seems the GitHub plugin is currently doing this, so maybe we just need to port that to the GitLab plugin. I tested this out with a test issue here, and GitHub indeed sends the whole issue description including the comment, so there must be something going on with the processing of the webhook

![CleanShot 2023-12-15 at 12 23 01](https://github.com/mattermost/mattermost-plugin-gitlab/assets/6913320/ec9ed8b5-0f22-4518-8ee3-8e285c99ab89)
![CleanShot 2023-12-15 at 12 24 02](https://github.com/mattermost/mattermost-plugin-gitlab/assets/6913320/a56878b1-d711-4c9c-a751-d9c33516133c)

**Comment by raghavaggarwal2308** [comment]
@svelle @wiggin77 I tried to reproduce the issue but seems like the comment markdown is already supported in the latest release of the plugin i.e. v1.9.1. This might have been fixed with some other issue. You can try to upgrade to the latest version if you are on an older version.
Please let me know if this is not supported for some particular case. I tried of for `issues` subscription.

![image](https://github.com/user-attachments/assets/847585d7-bea2-4787-8a61-ff20de679c3e)
![image](https://github.com/user-attachments/assets/b79609f0-d1f2-40a1-a7fc-e36a2b52d57b)

**Comment by raghavaggarwal2308** [comment]
Closing this issue for now. Can reopen if someone is still facing the issue
