### ISSUE TITLE
Bug - Gitlab sidebar icons visible even when not connected to GitLab

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-plugin-gitlab#467]
Refer this thread for more details - https://community.mattermost.com/core/pl/e6xfe7zue7dt3btib6spena6yy

![March 11 Screenshot from](https://github.com/mattermost/mattermost-plugin-gitlab/assets/18575143/2a9666ab-4316-4d37-86fa-174d0abb5113)

GitLab icons in LHS are visible even when you're not connected to GitLab in the plugin.

It reproduces in community.

**Comment by mickmister** [comment]
There was an existing issue in this repo that I moved to the monorepo for greater visibility for contributors https://github.com/mattermost/mattermost/issues/26433. We've been moving some HW tickets to the monorepo for this reason and have gotten more activity through that strategy. Probably better to copy them instead of move them though so there's a papertrail. I've done that sometimes, though this time chose to move it.

This probably should not be a HW ticket considering it seems like it's a regression that should be solved sooner than later. Thanks for filing the issue @harshilsharma63 :+1:
